version: '3'

services:

  tech-database:
    build: 
      context: ./database/
      dockerfile: Dockerfile

    restart: always

    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}

    # ports:
    #   - "27018:27017"

    volumes:
      - mongo:/data/db


  python-api:

    build: 
      context: ./python-api/
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    
    expose:
      - ${API_PORT}

    depends_on:
      - tech-database


  express-server:

    build: 
      context: ./express-server/
      dockerfile: Dockerfile

    environment:
      # - NODE_ENV=production
      - WEB_PORT=${WEB_PORT}
      - API_PORT=${API_PORT}
      - PORT_OUT=${PORT_OUT}
      
    ports:
      - "${PORT_OUT}:${WEB_PORT}"

    depends_on:
      - python-api


volumes:
  mongo: