version: '2'

services:

  tech-database:
    build: 
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: simen
      MONGO_INITDB_ROOT_PASSWORD: simenerkul

    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"


  python-api:
    build: 
      context: ./python-api/
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT}
    
    expose:
      - ${API_PORT}

    depends_on:
      - tech-database

  express-server:
    build: 
      context: ./express-server/
      dockerfile: Dockerfile

    environment:
      - WEB_PORT=${WEB_PORT}
      - API_PORT=${API_PORT}
      - PORT_OUT=${PORT_OUT}
      
    ports:
      - "${PORT_OUT}:${WEB_PORT}"

    depends_on:
      - python-api

volumes:
  mongo: